version: '3.4'

services:
  kledijmodule:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - TZ=Europe/Brussels
    container_name: kledijmodule_dev
    ports:
      - 5000:8080
      # - 5001:8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ./KledijModule/wwwroot:/app/wwwroot:rw
    
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container_dev
    restart: unless-stopped
    environment: #Complete list of env variables: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-2022
      - MSSQL_SA_PASSWORD=A&VeryComplex123Password!
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_DATA_DIR=/var/opt/mssql/data
      - MSSQL_LOG_DIR=/var/opt/mssql/logs
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backups
      - MSSQL_MEMORY_LIMIT_MB=4096
      - MSSQL_AGENT_ENABLED=true  #requires string, not bool
      - MSSQL_TCP_PORT=1433
      - MSSQL_COLLATION=Latin1_General_CI_AI
      - TZ=Europe/Brussels
    ports:
      - '1433:1433'
    volumes:
      - ./SQLServer/data:/var/opt/mssql/data  
      - ./SQLServer/logs:/var/opt/mssql/logs 
      - ./SQLServer/backups:/var/opt/mssql/backups  
